#!/bin/sh
echo 'into'
#.gempak
. /nwprod/gempak/.gempak

mkdir /stmp/wx20mg/gempak
mkdir /stmp/wx20mg/gempak/trop
rm /stmp/wx20mg/gempak/trop/*
cd /stmp/wx20mg/gempak/trop
cp /meso/save/wx20mg/casework/coltbl.xwp .

ymd=20130531

cycles="00 06 12 18"
for cyc in $cycles;do
times="48 84"
for fhr in $times; do

fmdl=/ptmp/wx20mg/monthly/namweekly_${ymd}${cyc}v${fhr}

    gdplot2 << EOF

 GDFILE   = $fmdl
 GDATTIM  = f$fhr 
 GLEVEL   = 500 
 GVCORD   = pres 
 GDPFUN   = mul(-1.,hghte)
 CINT     = 10 
 LINE     = 0 
 MAP      = 1
 WIND     = 0
 TITLE    = 1/-1/~   500 mb ANALYSIS / WEEKLY NAM ERRORS  ${cyc}z v${fhr}
 DEVICE   = GIF|500nam_${ymd}_${cyc}f0${fhr}.gif|750;900
 SATFIL   =
 RADFIL   =
 PROJ     = lcc/25;-100;25;/1;1;1;1
 GAREA    = 15.;-144.;73.;-36.
 CLEAR    = y
 PANEL    = 0
 TEXT     = 0.8/11/2/SW
 SCALE    = 0 
 LATLON   = 0
 HILO     = 0 
 HLSYM    = 0
 CLRBAR   = 1/H/UL/0.06;0.93/0.7;.02/1
 CONTUR   = 0
 SKIP     = 0
 FINT     = 0
 FLINE    = 0
 FINT     = -50;-40;-30;-20;-10;10;20;30;40;50
 FLINE    = 30;28;4;23;21;0;5;20;10;17;2
 TYPE     = f
 LUTFIL   =
 STNPLT   =
r

 GDPFUN   = quo(hght,10) 
 CINT     = 6
 LINE     = 1/1/3/1 
 TITLE    = 0
 CLEAR    = n
 FINT     = 0
 FLINE    = 0
 TYPE     = c
 FINT     = -50;-40;-30;-20;-10;10;20;30;40;50
 FLINE    = 30;28;5;23;21;0;5;20;10;17;2
r

ex
EOF

gpend
done
done

. /u/wx20mg/.Utils
export w1=wd20mg
export w2=$rzdm

ftp -n -v << EOF > /meso/save/wx20mg/casework/dwpfftp.out
open emcrzdm
user $w1 $w2
binary
cd /home/people/emc/www/htdocs/mmb/gmanikin/meg/stats
mput *.gif
bye
EOF

exit
