#!/bin/ksh
#@ output = /meso/save/wx20mg/monthly_mean/gfsmonthly.out
#@ error = /meso/save/wx20mg/monthly_mean/gfsmonthly.err
#@ job_type = parallel
#@ class = devhigh
#@ group = devonprod
#@ total_tasks = 1
#@ resources = ConsumableCpus(1) ConsumableMemory(2 GB)
#@ account_no=NAM-T2O
#@ wall_clock_limit = 00:49:00
#@ network.MPI = csss,shared,us
#@ queue
#

mkdir /stmp/wx20mg/gfsmonthly
rm /stmp/wx20mg/gfsmonthly/*
cd /stmp/wx20mg/gfsmonthly
cp /meso/save/wx20mg/gempak/nagrib/*tbl .

tmp1=2012080100
day1=`echo $tmp1 | cut -c1-8`
ym=`echo $tmp1 | cut -c1-6`

tmp2="`/meso/save/wx20mg/board/advtime ${tmp1} 24 -1`"
day2=`echo $tmp2 | cut -c1-8`
tmp3="`/meso/save/wx20mg/board/advtime ${tmp2} 24 -1`"
day3=`echo $tmp3 | cut -c1-8`
tmp4="`/meso/save/wx20mg/board/advtime ${tmp3} 24 -1`"
day4=`echo $tmp4 | cut -c1-8`
tmp5="`/meso/save/wx20mg/board/advtime ${tmp4} 24 -1`"
day5=`echo $tmp5 | cut -c1-8`
tmp6="`/meso/save/wx20mg/board/advtime ${tmp5} 24 -1`"
day6=`echo $tmp6 | cut -c1-8`
tmp7="`/meso/save/wx20mg/board/advtime ${tmp6} 24 -1`"
day7=`echo $tmp7 | cut -c1-8`
tmp8="`/meso/save/wx20mg/board/advtime ${tmp7} 24 -1`"
day8=`echo $tmp8 | cut -c1-8`
tmp9="`/meso/save/wx20mg/board/advtime ${tmp8} 24 -1`"
day9=`echo $tmp9 | cut -c1-8`
tmp10="`/meso/save/wx20mg/board/advtime ${tmp9} 24 -1`"
day10=`echo $tmp10 | cut -c1-8`
tmp11="`/meso/save/wx20mg/board/advtime ${tmp10} 24 -1`"
day11=`echo $tmp11 | cut -c1-8`
tmp12="`/meso/save/wx20mg/board/advtime ${tmp11} 24 -1`"
day12=`echo $tmp12 | cut -c1-8`
tmp13="`/meso/save/wx20mg/board/advtime ${tmp12} 24 -1`"
day13=`echo $tmp13 | cut -c1-8`
tmp14="`/meso/save/wx20mg/board/advtime ${tmp13} 24 -1`"
day14=`echo $tmp14 | cut -c1-8`
tmp15="`/meso/save/wx20mg/board/advtime ${tmp14} 24 -1`"
day15=`echo $tmp15 | cut -c1-8`
tmp16="`/meso/save/wx20mg/board/advtime ${tmp15} 24 -1`"
day16=`echo $tmp16 | cut -c1-8`
tmp17="`/meso/save/wx20mg/board/advtime ${tmp16} 24 -1`"
day17=`echo $tmp17 | cut -c1-8`
tmp18="`/meso/save/wx20mg/board/advtime ${tmp17} 24 -1`"
day18=`echo $tmp18 | cut -c1-8`
tmp19="`/meso/save/wx20mg/board/advtime ${tmp18} 24 -1`"
day19=`echo $tmp19 | cut -c1-8`
tmp20="`/meso/save/wx20mg/board/advtime ${tmp19} 24 -1`"
day20=`echo $tmp20 | cut -c1-8`
tmp21="`/meso/save/wx20mg/board/advtime ${tmp20} 24 -1`"
day21=`echo $tmp21 | cut -c1-8`
tmp22="`/meso/save/wx20mg/board/advtime ${tmp21} 24 -1`"
day22=`echo $tmp22 | cut -c1-8`
tmp23="`/meso/save/wx20mg/board/advtime ${tmp22} 24 -1`"
day23=`echo $tmp23 | cut -c1-8`
tmp24="`/meso/save/wx20mg/board/advtime ${tmp23} 24 -1`"
day24=`echo $tmp24 | cut -c1-8`
tmp25="`/meso/save/wx20mg/board/advtime ${tmp24} 24 -1`"
day25=`echo $tmp25 | cut -c1-8`
tmp26="`/meso/save/wx20mg/board/advtime ${tmp25} 24 -1`"
day26=`echo $tmp26 | cut -c1-8`
tmp27="`/meso/save/wx20mg/board/advtime ${tmp26} 24 -1`"
day27=`echo $tmp27 | cut -c1-8`
tmp28="`/meso/save/wx20mg/board/advtime ${tmp27} 24 -1`"
day28=`echo $tmp28 | cut -c1-8`

hours="00 06 12 18 24 30 36 42 48 54 60 66 72 78 84"
hours="24 48 60 84"
set -x

cycles="00 06 12 18"
for cyc in $cycles; do
for fhr in $hours; do

COMOUT=/meso/noscrub/wx20mg/monthly/gfs
COMIN=/meso/noscrub/wx20mg/monthly/gfs
EXECutil=/nwprod/util/exec
EXEC=/meso/save/wx20mg/monthly_mean/exec
mkdir $COMOUT

# Set up some constants
export XLFRTEOPTS="unit_vars=yes"
export tmmark=tm00
export MP_SHARED_MEMORY=yes

cp ${COMIN}/gfsmean_${day1}${cyc}V${fhr} GFS1
$EXECutil/grbindex GFS1 GFS1I 
cp ${COMIN}/gfsmean_${day2}${cyc}V${fhr} GFS2
$EXECutil/grbindex GFS2 GFS2I
cp ${COMIN}/gfsmean_${day3}${cyc}V${fhr} GFS3
$EXECutil/grbindex GFS3 GFS3I
cp ${COMIN}/gfsmean_${day4}${cyc}V${fhr} GFS4
$EXECutil/grbindex GFS4 GFS4I
cp ${COMIN}/gfsmean_${day5}${cyc}V${fhr} GFS5
$EXECutil/grbindex GFS5 GFS5I
cp ${COMIN}/gfsmean_${day6}${cyc}V${fhr} GFS6
$EXECutil/grbindex GFS6 GFS6I
cp ${COMIN}/gfsmean_${day7}${cyc}V${fhr} GFS7
$EXECutil/grbindex GFS7 GFS7I
cp ${COMIN}/gfsmean_${day8}${cyc}V${fhr} GFS8
$EXECutil/grbindex GFS8 GFS8I
cp ${COMIN}/gfsmean_${day9}${cyc}V${fhr} GFS9
$EXECutil/grbindex GFS9 GFS9I
cp ${COMIN}/gfsmean_${day10}${cyc}V${fhr} GFS10
$EXECutil/grbindex GFS10 GFS10I
cp ${COMIN}/gfsmean_${day11}${cyc}V${fhr} GFS11
$EXECutil/grbindex GFS11 GFS11I
cp ${COMIN}/gfsmean_${day12}${cyc}V${fhr} GFS12
$EXECutil/grbindex GFS12 GFS12I
cp ${COMIN}/gfsmean_${day13}${cyc}V${fhr} GFS13
$EXECutil/grbindex GFS13 GFS13I
cp ${COMIN}/gfsmean_${day14}${cyc}V${fhr} GFS14
$EXECutil/grbindex GFS14 GFS14I
cp ${COMIN}/gfsmean_${day15}${cyc}V${fhr} GFS15
$EXECutil/grbindex GFS15 GFS15I
cp ${COMIN}/gfsmean_${day16}${cyc}V${fhr} GFS16
$EXECutil/grbindex GFS16 GFS16I
cp ${COMIN}/gfsmean_${day17}${cyc}V${fhr} GFS17
$EXECutil/grbindex GFS17 GFS17I
cp ${COMIN}/gfsmean_${day18}${cyc}V${fhr} GFS18
$EXECutil/grbindex GFS18 GFS18I
cp ${COMIN}/gfsmean_${day19}${cyc}V${fhr} GFS19
$EXECutil/grbindex GFS19 GFS19I
cp ${COMIN}/gfsmean_${day20}${cyc}V${fhr} GFS20
$EXECutil/grbindex GFS20 GFS20I
cp ${COMIN}/gfsmean_${day21}${cyc}V${fhr} GFS21
$EXECutil/grbindex GFS21 GFS21I
cp ${COMIN}/gfsmean_${day22}${cyc}V${fhr} GFS22
$EXECutil/grbindex GFS22 GFS22I
cp ${COMIN}/gfsmean_${day23}${cyc}V${fhr} GFS23
$EXECutil/grbindex GFS23 GFS23I
cp ${COMIN}/gfsmean_${day24}${cyc}V${fhr} GFS24
$EXECutil/grbindex GFS24 GFS24I
cp ${COMIN}/gfsmean_${day25}${cyc}V${fhr} GFS25
$EXECutil/grbindex GFS25 GFS25I
cp ${COMIN}/gfsmean_${day26}${cyc}V${fhr} GFS26
$EXECutil/grbindex GFS26 GFS26I
cp ${COMIN}/gfsmean_${day27}${cyc}V${fhr} GFS27
$EXECutil/grbindex GFS27 GFS27I
cp ${COMIN}/gfsmean_${day28}${cyc}V${fhr} GFS28
$EXECutil/grbindex GFS28 GFS28I

    export XLFUNIT_11="GFS1"
    export XLFUNIT_12="GFS1I"
    export XLFUNIT_13="GFS2"
    export XLFUNIT_14="GFS2I" 
    export XLFUNIT_15="GFS3"
    export XLFUNIT_16="GFS3I"
    export XLFUNIT_17="GFS4"
    export XLFUNIT_18="GFS4I" 
    export XLFUNIT_19="GFS5"
    export XLFUNIT_20="GFS5I" 
    export XLFUNIT_21="GFS6"
    export XLFUNIT_22="GFS6I"
    export XLFUNIT_23="GFS7"
    export XLFUNIT_24="GFS7I" 
    export XLFUNIT_25="GFS8"
    export XLFUNIT_26="GFS8I"
    export XLFUNIT_27="GFS9"
    export XLFUNIT_28="GFS9I"
    export XLFUNIT_29="GFS10"
    export XLFUNIT_30="GFS10I" 
    export XLFUNIT_31="GFS11"
    export XLFUNIT_32="GFS11I"
    export XLFUNIT_33="GFS12"
    export XLFUNIT_34="GFS12I"
    export XLFUNIT_35="GFS13"
    export XLFUNIT_36="GFS13I"
    export XLFUNIT_37="GFS14"
    export XLFUNIT_38="GFS14I"
    export XLFUNIT_39="GFS15"
    export XLFUNIT_40="GFS15I"
    export XLFUNIT_41="GFS16"
    export XLFUNIT_42="GFS16I"
    export XLFUNIT_43="GFS17"
    export XLFUNIT_44="GFS17I" 
    export XLFUNIT_45="GFS18"
    export XLFUNIT_46="GFS18I"
    export XLFUNIT_47="GFS19"
    export XLFUNIT_48="GFS19I"
    export XLFUNIT_49="GFS20"
    export XLFUNIT_50="GFS20I" 
    export XLFUNIT_51="GFS21"
    export XLFUNIT_52="GFS21I"
    export XLFUNIT_53="GFS22"
    export XLFUNIT_54="GFS22I"
    export XLFUNIT_55="GFS23"
    export XLFUNIT_56="GFS23I"
    export XLFUNIT_57="GFS24"
    export XLFUNIT_58="GFS24I"
    export XLFUNIT_59="GFS25"
    export XLFUNIT_60="GFS25I"
    export XLFUNIT_61="GFS26"
    export XLFUNIT_62="GFS26I"
    export XLFUNIT_63="GFS27"
    export XLFUNIT_64="GFS27I" 
    export XLFUNIT_65="GFS28"
    export XLFUNIT_66="GFS28I"
    export XLFUNIT_78="GFSMEANFIL${fhr}"
    $EXEC/monthly_stats_28 <<EOF >> gfsmonthly.out${fhr}
$fhr
EOF

   nagrib  <<  EOF
 GBFILE   = GFSMEANFIL${fhr}
 INDXFL   =
 GDOUTF   = gfsmonthly_${ym}${cyc}V${fhr}
 PROJ     = MER
 GRDAREA  =
 KXKY     = 10;10
 MAXGRD   = 2000
 CPYFIL   = gds
 GAREA    = grid
 OUTPUT   = t
 GBTBLS   =
 GBDIAG   =
 PDSEXT   = NO
 OVERWR   = NO
r

ex
EOF

cp gfsmonthly_${ym}${cyc}V${fhr} /ptmp/wx20mg/monthly/gfsmonthly_${ym}${cyc}V${fhr}
done
done
exit
